### ISSUE TITLE
dYdX position does not match to Tradingview Position

### ISSUE THREAD

**Issue by layhau** [junta/tradingview-alert-connector#1]
I'm using "size": "{{strategy.order.contracts}}" for size of the trade, but it's getting warning "dYdX position does not match to Tradingview Position" every time a trade is placed. Is there a way to fix the trade size based on % of equity available in dYdX?

**Comment by junta** [comment]
For the time being, You can ignore this warning as long as your position on dydx is correct(=matches to position on Tradingview)

This warning does not affect order execution to dydx.
I'll improve the logic of throwing this error later.

**Comment by junta** [comment]
I concluded this function is unnecessary and removed this warning alert in the latest version
