### ISSUE TITLE
Thank You, Quick Questions

### ISSUE THREAD

**Issue by jonathanhyunsung** [junta/tradingview-alert-connector#19]
Hi, love your work.

Notes Related to GMX Support:
- Will there be support for Market Orders? When filling in different prices for opening and closing a position, it behaves similar to Limit Orders.
   - Opens and closes positions fine when the input price is close to the mark price. 
   - For example, if the input price deviates too much from the mark price, it won't open / close the position.
   - Used Insomnia, great tool for checking webhooks.
- Will there be support for different collaterals besides USDC?

Thank you very much for your work.

**Comment by junta** [comment]
Hi, which exchange are you referring to? (dydx or Perpetual Protocol or GMX)

maybe we can talk in DM
https://twitter.com/CryptoIbuki

**Comment by junta** [comment]
hey!
I'm considering supporting them, especially the second one(support collaterals besides USDC)
if users have needs

maybe we can talk in DM
https://twitter.com/CryptoIbuki
