### ISSUE TITLE
Love the Connector, Follow Up Question

### ISSUE THREAD

**Issue by jonathanhyunsung** [junta/tradingview-alert-connector#23]
Hi, again I wanna say thank you for your work,
I wanted to see if you're going to add non-USDC function to GMX please?
I also wrote to your email at j-----t------@--------- if you'd like to speak there.

Thank you again!

**Comment by junta** [comment]
hey!

yes, I'm going to add non-USDC soon, ideally by the end of this month. 

appreciate your comment and feedback!
