### ISSUE TITLE
Error: Query failed with (22): rpc error: code = NotFound desc = account ( subaccount address ) not found: key not found

### ISSUE THREAD

**Issue by dydxhedgie** [junta/tradingview-alert-connector#27]
Hello! I've been trying to get dydxv4 to work but can't seem to stop the error "Error on getting account data" Ive used latest commit and deposited collateral. I just transferred the USDC to a new account to see if that works. Will update

**Comment by dydxhedgie** [comment]
I did deposit using coinbase directly to dydx, and not my wallet, could that be the cause?

**Comment by junta** [comment]
hey deposit using coinbase directly to dydx should be okay.

Did you export your secret phrase in the way described here?
https://tv-connector.gitbook.io/docs/setup/dydx-v4-setup#export-your-secret-phrase-a-set-of-24-words-from-dxdx-website-then-put-it-in-.env-file

It's not the same as your original secret phrase

**Comment by dydxhedgie** [comment]
thanks for the reply, I did it as shown above and I can tell the secret phase worked because in the log it says "path: '/v4/addresses/dydx1vz2078q9k6qjwyxeqh35h79044yc5v5fxqaa9n/subaccountNumber/0',
      _ended: true," and when I was doing it wrong earlier it said wrong mnemonic

**Comment by junta** [comment]
hmm okay

so maybe it's coinbase wallet specific issue, I'll install and try it later

For the time being, could you try with metamask if you don't mind?

**Comment by dydxhedgie** [comment]
I will try and deposit a little, the gwei is just very high so ill have to see if I can :) Thanks for the quick response

**Comment by dydxhedgie** [comment]
I deposited a little matic successfully, cleared cached and redeployed and unfortunately im still getting the error "Error on getting account data"

**Comment by dydxhedgie** [comment]
TypeError: Cannot read properties of undefined (reading 'getBalance')
    at /app/dist/services/gmx/getAccount.js:18:38
    at Generator.next (<anonymous>)
    at /app/dist/services/gmx/getAccount.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/services/gmx/getAccount.js:4:12)
    at gmxGetAccount (/app/dist/services/gmx/getAccount.js:15:29)
    at /app/dist/controllers/index.js:30:40
    at Generator.next (<anonymous>)
    at /app/dist/controllers/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/controllers/index.js:4:12)
    at /app/dist/controllers/index.js:25:31
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
Address: dydx1vz2078q9k6qjwyxeqh35h79044yc5v5fxqaa9n
class AxiosServerError extends AxiosError {
    constructor(response, originalError) {
        super(`${response.status}: ${response.statusText} - ${JSON.stringify(response.data, null, 2)}`, originalError);
        this.status = response.status;
        this.statusText = response.statusText;
        this.data = response.data;
    }
}: 404: Not Found - {
  "errors": [
    {
      "msg": "No subaccount found with address (dydx address) and subaccountNumber 0"
    }
  ]
}
    at axiosRequest (/app/node_modules/@dydxprotocol/v4-client-js/build/src/clients/lib/axios/axiosRequest.js:19:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AccountClient.get (/app/node_modules/@dydxprotocol/v4-client-js/build/src/clients/modules/rest.js:18:26) {
  originalError: AxiosError: Request failed with status code 404
      at settle (/app/node_modules/@dydxprotocol/v4-client-js/node_modules/axios/dist/node/axios.cjs:1268:12)
      at BrotliDecompress.handleStreamEnd (/app/node_modules/@dydxprotocol/v4-client-js/node_modules/axios/dist/node/axios.cjs:2446:11)
      at BrotliDecompress.emit (node:events:526:35)
      at BrotliDecompress.emit (node:domain:488:12)
      at endReadableNT (node:internal/streams/readable:1589:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ERR_BAD_REQUEST',
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [AxiosHeaders],
      url: 'https://indexer.dydx.trade/v4/addresses/(dydx address)/subaccountNumber/0',
      method: 'get',
      data: undefined
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'GET /v4/addresses/(dydx address)/subaccountNumber/0 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.1.3\r\n' +
        'Accept-Encoding: gzip, deflate, br\r\n' +
        'Host: indexer.dydx.trade\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v4/addresses/(dydx address)/subaccountNumber/0',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: 'indexer.dydx.trade',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    response: {
      status: 404,
      statusText: 'Not Found',
      headers: [AxiosHeaders],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    }
  },
  status: 404,
  statusText: 'Not Found',
  data: { errors: [ [Object] ] }
}

**Comment by dydxhedgie** [comment]
log above, I just removed the dydx addresses, not sure if those are to be kept private

**Comment by junta** [comment]
hey, do you still have this issue?
I can't reproduce it on my end.
Are you sure your account is ready to trade?

**Comment by dydxhedgie** [comment]
I'll try again now, will update you soon

**Comment by dydxhedgie** [comment]
yes my account is ready to trade, I placed a tiny trade to see if I could and everything is fine, I have $400 as collateral

**Comment by dydxhedgie** [comment]
just tested it now and it says the same error, is there a step that I could be messing up that would cause this?

**Comment by squibwarb** [comment]
Hey @dydxhedgie, does your `ETH_ADDRESS` in your .env file start with `dydx`? For dydx v4 you have to use your dydx chain address (which starts with `dydx`), not the source address (which typically starts with `0x`). Maybe that is the issue?

**Comment by dydxhedgie** [comment]
Oh wow, I didn't know you had to include the v3 parameters in the v4 env file! I only put in the secret phrase. v4 tutorial is a bit confusing. Thanks for letting me know! Ill try this now it should fix it

**Comment by squibwarb** [comment]
Actually, my bad. I was able to get it working with JUST `DYDX_V4_MNEMONIC` in my .env file.. no eth_address or any other fields. It must be a typo on your mnemonic or something like that. Or you're using the mnemonic for a mainnet wallet in the development config (or vice versa). Sorry for the confusion!

**Comment by dydxhedgie** [comment]
all good, sadly still not working even with the mnemonic correctly pasted. Not sure why its just an error on my side.

**Comment by dydxhedgie** [comment]
i am so silly! Please in the dydx v4 tutorial tell people to use MAIN branch, I selected dydxv4 since it seemed like the correct thing to do. Sorry and thanks for all the help guys!

**Comment by junta** [comment]
ah I see!
I've deleted the branch so that any other guys don't make the same mistake

**Comment by dydxhedgie** [comment]
thank you!! have a great rest of your night and thank you so much for this tool
