### ISSUE TITLE
strategydata undefined

### ISSUE THREAD

**Issue by adrien44** [junta/tradingview-alert-connector#6]
Hi, 
Thank a lot for your work.

I tried your web service but I can not make it works perfectly.
It follows my alert but sometimes I get this error which break my strategy : 

` strategyData undefined
  /app/dist/services/validateAlert.js:5
         function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                          ^
 TypeError: Cannot read properties of undefined (reading 'isFirstOrder')
     at /app/dist/services/validateAlert.js:92:41
     at Generator.next (<anonymous>)
     at fulfilled (/app/dist/services/validateAlert.js:5:58)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
 error Command failed with exit code 1.
 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 yarn run v1.22.18
 $ tsc && NODE_ENV=production ts-node dist/index.js
 TV-Connector web server listening on port 10000`

Can you help me understand it ?
Thanks for your time

**Comment by junta** [comment]
Hi,
At where are you hosting this tool? Render.com?

**Comment by adrien44** [comment]
Yes. I followed your tuto and did exactly the same.

**Comment by adrien44** [comment]
the tradingview strategy is fairly simple. Only long position. Only one trade at a time. Buy then sell and so on.

**Comment by junta** [comment]
I see, 
Have you set up the Disk feature on Render.com?
https://tv-connector.gitbook.io/docs/setuup/run-on-cloud-service

<img width="940" alt="Screen Shot 2023-02-10 at 11 18 32" src="https://user-images.githubusercontent.com/1056248/217983670-d0f9acb5-9275-48fc-9336-d1fe46408ce8.png">

**Comment by adrien44** [comment]
Yes 
![Screenshot_20230210-034447_Chrome](https://user-images.githubusercontent.com/4097397/217987517-43c8bd96-0d16-465d-8574-a6254ebdd0e8.jpg)

**Comment by junta** [comment]
1. What is your strategy name?
2. Can you redeploy the code to your web service?

at your web service page of Render.com, go to Manual deploy -> deploy latest commit

<img width="358" alt="Screen Shot 2023-02-10 at 11 52 57" src="https://user-images.githubusercontent.com/1056248/217989644-4b1627bf-e578-4c89-9086-04f72d84f9de.png">

**Comment by adrien44** [comment]
Do the strategy name must match something ? 
My strategy name on trading view was BOT ETH/USD, I gave the alert the same name.
I already redeployed the code and even recreated a web service from scratch. (Yesterday)

**Comment by junta** [comment]
No, the strategy name does not need to be matched something.
Could you try changing your strategy name to "BOT ETHUSD", for example?
remove  "/" from your strategy name.

**Comment by adrien44** [comment]
I will try that and get back to you. 
Thanks

**Comment by adrien44** [comment]
Hi Junta,
I just re-start a strategy after removing  "/" in the name as you suggested. So far, it's working (following correctly the orders from tradingview strategy).
I will let it run for a few days and keep you posted on the results.

**Comment by adrien44** [comment]
Hi,
4 days and everything works great.
Thanks for your time on this !

**Comment by junta** [comment]
Yes, you can set alert of 2 different currencies on the same service.

Do you give a different strategy name to ETH and AVAX bot?

**Comment by adrien44** [comment]
I used the same script name "Bot crypto" but created 2 alerts.

First one name : Bot AVAX with this message :
`{
	"exchange": "dydx",
	"strategy": "Bot AVAXUSD",
	"market": "AVAX_USD",
	"size": "{{strategy.order.contracts}}",
	"reverse": false,
	"order": "{{strategy.order.action}}",
	"position": "{{strategy.market_position}}",
	"price": "{{strategy.order.price}}",
	"passphrase": ""
}`

Second one : Bot ETH with this message
`{
	"exchange": "dydx",
	"strategy": "Bot ETHUSD",
	"market": "ETH_USD",
	"size": "{{strategy.order.contracts}}",
	"reverse": false,
	"order": "{{strategy.order.action}}",
	"position": "{{strategy.market_position}}",
	"price": "{{strategy.order.price}}",
	"passphrase": ""
}`

**Comment by junta** [comment]
Hmm, I don't get why this happens.
Could you try several other alerts triggered with a minimum amount and check whether the same error happens?

**Comment by adrien44** [comment]
Ok, I will test it and get back to you
