### ISSUE TITLE
AxiosServerError: 429: Too Many Requests - "error code: 1015"

### ISSUE THREAD

**Issue by Pi-Rr** [junta/tradingview-alert-connector#7]
Hi @junta, love your dydx<>TradingView integration, have been using it for 4 months now, thanks a lot for making that!
I have set it up exactly as described in your tutorial video, using Render, the Doker image and Sentry for monitoring.

I have a few strategies running on several symbols at the same time, and from time to time, in period of high volatility I get a lot order triggering at th same time, and this result is some orders being not executed and the following error in Sentry: _AxiosServerError: 429: Too Many Requests - "error code: 1015"_
Do you know if that is an issue on TradingView side (and in that case there is nothing I can do I guess, beside reducing the number of strategies), or is it an issue on Render side that could be solved by buying a more powerful server?

Many thanks for your help :)

**Comment by junta** [comment]
hey,
dydx v3 has rate limiting as described below
https://dydxprotocol.github.io/v3-teacher/#rate-limit-api
