### ISSUE TITLE
Size is not doubled when going from Long to Short. Skipping an exit.

### ISSUE THREAD

**Issue by thisisloze** [junta/tradingview-alert-connector#8]
{
    "exchange": "dydx",
    "strategy": "strat",
    "market": "ETH_USD",
    "size": "0.045",
    "reverse": false,
    "order": "buy",
    "position": "long",
    "price": "1800.8000000000002"
}
followed by 
{
    "exchange": "dydx",
    "strategy": "strat",
    "market": "ETH_USD",
    "size": "0.045",
    "reverse": false,
    "order": "sell",
    "position": "short",
    "price": "1768.7"
}

Ends up being flat rather then ending up being short.

**Comment by junta** [comment]
Hey 
please set `"reverse": true` in your parameter.
